### ISSUE TITLE
Request: tool made from the techniques used to find custom seeds.

### ISSUE THREAD

**Issue by BuyMyMojo** [minecrafthome/b1.7_seedfinder#4]
Woulkd it be possible to get a tool made that uses the code and ideas here combined into an easy to use tool for anyone to find custom seeds?

**Comment by Earthcomputer** [comment]
Every image requires different methodology to reverse, so there is no one-size-fits-all program. If you want to crack a seed from an image, you probably have to know how to code and mix and match existing code
